spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active:
      - local

    group:
      local:
        - local-config
        - cloud
        - auth

openbanking:
  client_id: 3d6b00d9-cac5-4d7f-8f2a-22adf8791a2d
  client_secret: 531865df-1f25-4464-92fa-ec3231a6dfd2
  redirect:
    uri: https://localhost:8080/api/v1/openapi/usercertification
  api:
    base-url: https://testapi.openbanking.or.kr


bucl_system:
  reward:
    withdrawal:
      minimum_amt: 5000
