cloud:
  aws:
    credentials:
      access-key: AKIAQJ2XNPL3YB5BTH47
      secret-key: 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
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false