spring:
  profiles:
    active:
      - local

    group:
      local:
        - local-config
        - cloud

crypto:
  secretkey: mvptestbuclfrien         #32자까지
  iv: buclaskdniop2was                #16자까지